# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# deploys built code to gh-pages
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --prod

      - name: Setup SPA
        run: cp dist/talk-to-me-frontend/index.html dist/talk-to-me-frontend/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/talk-to-me-frontend
          cname: talk-to-me.co
