# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Tests

on: [push, pull_request]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-latest

    steps:
      - name: Setup backend
        uses: actions/checkout@v1
        with:
          repository: "talk-with-me/talk-to-me-backend"
          ref: main
          path: backend
      - name: Build backend
        run: cd $GITHUB_WORKSPACE/backend && docker-compose up --build -d && cd ..
      - name: Clone repo
        uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install dependencies
        run: npm install
      - name: E2E
        run: npm run e2e -- --configuration=ci

